apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-user-service.fullname" . }}-config
  labels:
    {{- include "core-user-service.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Values.app.serviceName | quote }}
  SERVICE_VERSION: {{ .Values.app.serviceVersion | quote }}
  ENV: {{ .Values.app.env | quote }}
  PORT: {{ .Values.app.port | quote }}
  LOG_LEVEL: {{ .Values.app.logLevel | quote }}

  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_USERNAME: {{ .Values.database.username | quote }}
  DATABASE_ECHO: {{ .Values.database.echo | quote }}

  ALGORITHM: {{ .Values.security.algorithm | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.security.accessTokenExpireMinutes | quote }}

  CORS_ORIGINS: {{ .Values.cors.origins | toJson | quote }}

  PYTHONPATH: {{ .Values.python.path | quote }}
  PYTHONUNBUFFERED: {{ .Values.python.unbuffered | quote }}