apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-user-service.fullname" . }}
  labels:
    app: {{ include "core-user-service.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "core-user-service.name" . }}
  template:
    metadata:
      labels:
        {{- include "core-user-service.selectorLabels" . | nindent 8 }}
        app: {{ include "core-user-service.name" . }}
        version: {{ .Chart.AppVersion | default "v1" }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}