{{- if and .Values.istio.enabled .Values.istio.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "core-user-service.fullname" . }}
  labels:
    {{- include "core-user-service.labels" . | nindent 4 }}
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "core-user-service.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}