apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-user-service.fullname" . }}-secret
  labels:
    {{- include "core-user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.database.password | quote }}

  SECRET_KEY: {{ .Values.security.secretKey | quote }}