apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-user-service.fullname" . }}
  labels:
    app: {{ include "core-user-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "core-user-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}