auth:
  strategy: anonymous

external_services:
  prometheus:
    url: http://prometheus-server.istio-system:80
  grafana:
    enabled: false  # Disable Grafana for now
  custom_dashboards:
    enabled: false  # Disable since no Grafana
  istio:
    root_namespace: istio-system
  tracing:
    enabled: false

server:
  web_root: /kiali
  observability:
    metrics:
      enabled: true
      port: 9090
  port: 20001

deployment:
  pod_labels:
    sidecar.istio.io/inject: "false"
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 10m
      memory: 64Mi