apiVersion: v1
kind: Secret
metadata:
  name: core-user-service-secret
  namespace: visiobook-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"  # Deploy before postgres Cluster and all services
  labels:
    app: core-user-service-secret
type: Opaque
stringData:

  SYNC_WAVE: "0"