apiVersion: v1
kind: Secret
metadata:
  name: postgres-crud-project-secret
  namespace: visiobook-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: postgres-crud
type: Opaque
stringData:
  # ===== Application connection (core-project-service) =====
  DATABASE_URL: "postgresql://core_project_app:ProjectPass123!@postgres-crud-rw.visiobook-namespace.svc.cluster.local:5432/core_project"
  DB_HOST: "postgres-crud-rw.visiobook-namespace.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "core_project"
  DB_USERNAME: "core_project_app"
  DB_PASSWORD: "ProjectPass123!"
