apiVersion: v1
kind: Secret
metadata:
  name: postgres-io-ingestion-secret
  namespace: visiobook-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: postgres-io
type: Opaque
stringData:
  # ===== Application connection (content-ingestion-service) =====
  DATABASE_URL: "postgresql://ingestion_user:IngestionPass123!@postgres-io-rw.visiobook-namespace.svc.cluster.local:5432/ingestion"
  DB_HOST: "postgres-io-rw.visiobook-namespace.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "ingestion"
  DB_USERNAME: "ingestion_user"
  DB_PASSWORD: "IngestionPass123!"
