apiVersion: v1
kind: Secret
metadata:
  name: postgres-io-analysis-secret
  namespace: visiobook-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    app: postgres-io
type: Opaque
stringData:
  # ===== Application connection (ai-analysis-service) =====
  DATABASE_URL: "postgresql://analysis_user:AnalysisPass123!@postgres-io-rw.visiobook-namespace.svc.cluster.local:5432/analysis"
  DB_HOST: "postgres-io-rw.visiobook-namespace.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "analysis"
  DB_USERNAME: "analysis_user"
  DB_PASSWORD: "AnalysisPass123!"
