{{- if and .Values.istio .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "web-user-portal.fullname" . }}
  labels:
    {{- include "web-user-portal.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ include "web-user-portal.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "web-user-portal.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}