replicaCount: 1

image:
  repository: ghcr.io/visiobook-esp/core-database-service-dev
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  nodePort: 30085

nameOverride: ""
fullnameOverride: "core-database-service"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  annotations: {}
  name: ""

istio:
  enabled: true
  injection: true

  virtualService:
    enabled: true
    hosts:
      - "core-database-service"
      - "core-database-service.visiobook.dev"
    gateways:
      - mesh
  destinationRule:
    enabled: true
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
        http:
          http1MaxPendingRequests: 100
          http2MaxRequests: 100
          maxRequestsPerConnection: 2
      loadBalancer:
        simple: ROUND_ROBIN
      outlierDetection:
        consecutiveErrors: 5
        interval: 30s
        baseEjectionTime: 30s

  mtls:
    enabled: true
    mode: ISTIO_MUTUAL

nodeSelector: {}
tolerations: []
affinity: {}

podLabels:
  app: core-database-service
  version: "latest"
  app.kubernetes.io/name: core-database-service
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: database

resources: {}
env:
  DATABASE_URL: postgresql://postgres:password@postgres-core-database.database.svc.cluster.local:6432/visiobook_dev
  DB_MAX_CONNECTIONS: 10
  DB_CONNECTION_TIMEOUT: 30000
  REDIS_HOST: redis.database.svc.cluster.local
  REDIS_PORT: 6379
  REDIS_PASSWORD:
  REDIS_DB: 0
  NODE_ENV: development
  PORT: 3000
  CORS_ORIGINS: *
  LOG_LEVEL: debug
  API_VERSION: v1
  API_PREFIX: api
  JWT_SECRET: blablablablalblalbla
  JWT_EXPIRES_IN: 24h
  ENABLE_METRICS: true
  METRICS_PORT: 9090
