apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application-visobook
  namespace: argocd
spec:
  description: VisioBook applications

  sourceRepos:
    - 'https://github.com/VisioBook-ESP/*'
    - 'https://cloudnative-pg.github.io/charts'

  destinations:
    - namespace: visiobook-namespace
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'