apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-visobook
spec:
  destination:
    namespace: visiobook-namespace
    server: https://kubernetes.default.svc

  source:
    repoURL: >-
      https://github.com/VisioBook-ESP/infra-helm-charts
    path: environnement/charts/*
    targetRevision: 33-1-application-par-pod-to-applciation-pour-tous-les-pods
    # helm:
    #   valueFiles:
    #     - ../../charts/application-values.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true










































