apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-visiobook
  namespace: argocd
spec:
  destination:
    namespace: visiobook-namespace
    server: https://kubernetes.default.svc

  sources:

    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.22.1
      helm:
        values: |
          monitoring:
            podMonitorEnabled: true

    # PostgreSQL Cluster (sync-wave 1)
    - repoURL: https://github.com/VisioBook-ESP/infra-helm-charts  # Your repo
      path: ../../../charts/cloud-native-postgres/  # or postgres-cluster/charts/
      targetRevision: 35-creer-un-chart-cnpg
      helm:
        valueFiles:
          - values.yaml

    - repoURL: https://github.com/VisioBook-ESP/support-storage-service
      path: charts/
      targetRevision: dev
      helm:
        valueFiles:
          - values.yaml

    - repoURL: https://github.com/VisioBook-ESP/ai-analysis-service
      path: charts/
      targetRevision: dev
      helm:
        valueFiles:
          - values.yaml

    - repoURL: https://github.com/VisioBook-ESP/core-user-service
      path: charts/
      targetRevision: dev
      helm:
        valueFiles:
          - values.yaml

    # - repoURL: https://github.com/VisioBook-ESP/web-user-portal
    #   path: charts/
    #   targetRevision: dev
    #   helm:
    #     valueFiles:
    #       - values.yaml

    # - repoURL: https://github.com/VisioBook-ESP/core-project-service
    #   path: charts/
    #   targetRevision: dev
    #   helm:
    #     valueFiles:
    #       - values.yaml

  project: application-visobook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m