apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-visiobook
  namespace: argocd
spec:
  destination:
    namespace: visiobook-namespace
    server: https://kubernetes.default.svc

  sources:
    - repoURL: https://github.com/VisioBook-ESP/infra-helm-charts
      path: environnement/dev/charts/support-storage-service
      targetRevision: 33-1-application-par-pod-to-applciation-pour-tous-les-pods
      helm:
        valueFiles:
          - values.yaml
          
    - repoURL: https://github.com/VisioBook-ESP/infra-helm-charts
      path: environnement/dev/charts/ai-analysis-service
      targetRevision: 33-1-application-par-pod-to-applciation-pour-tous-les-pods
      helm:
        valueFiles:
          - values.yaml
  project: application-visobook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
