{{- if .Values.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "redis-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-db.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redis-db.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.istio.peerAuthentication.mode }}
{{- end }}