{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis-db.fullname" . }}-pvc
  labels:
    {{- include "redis-db.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode }}
  {{- if .Values.redis.persistence.storageClass }}
  {{- if (eq "-" .Values.redis.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}