{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis.fullname" . }}-pvc
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.redis.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
  {{- if .Values.redis.persistence.storageClass }}
  {{- if (eq "-" .Values.redis.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}