apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-db.fullname" . }}
  labels:
    {{- include "redis-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "redis-db.selectorLabels" . | nindent 4 }}