apiVersion: v2
name: visiobook-all
description: Umbrella chart for all VisioBook services
type: application
version: 1.0.0

dependencies:
  - name: core-user-service
    version: "*"
    repository: file://./core-user-service
    
  - name: core-project-service
    version: "*"
    repository: file://./core-project-service
    