apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: contact@visiobook.cloud
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            ingressClassName: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: visiobook-tls
  namespace: istio-system    # meme namespace que le gateway
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  secretName: visiobook-tls-secret   # le nom reference dans ton gateway
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - visiobook.cloud