apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-analysis-service.fullname" . }}
  labels:
    app: {{ include "ai-analysis-service.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ai-analysis-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "ai-analysis-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083   # ⚠️ correspond au port où Uvicorn écoute
          env:
            {{- range $key, $value := .Values.env }}
            support-storage-service- name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}