apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-analysis-service.fullname" . }}
  labels:
    app: {{ include "ai-analysis-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ai-analysis-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}       # 80 côté service
      targetPort: 8083                       # ⚠️ vers le container port
      nodePort: {{ .Values.service.nodePort }} # 30080 exposé sur Minikube
