apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-analysis-service.fullname" . }}
  labels:
    app: {{ include "ai-analysis-service.name" . }}
    version: {{ .Values.image.tag | quote }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ai-analysis-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}