{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "core-database-service.fullname" . }}
  labels:
    {{- include "core-database-service.labels" . | nindent 4 }}
spec:
  host: {{ include "core-database-service.fullname" . }}
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
    {{- if .Values.istio.mtls.enabled }}
    tls:
      mode: {{ .Values.istio.mtls.mode }}
    {{- end }}
{{- end }}