name: Helm Unit Tests

on:
  push:
    branches: ["**"]     # triggers on ALL branches
  pull_request:
    branches: ["dev"] 

permissions:
  contents: read
  packages: write

jobs:
  minikube:
      name: ğŸ—ï¸ Deploy & Test ALL Charts on Minikube
      runs-on: ubuntu-latest
      needs: kubeval
      steps:
        - uses: actions/checkout@v4
        - name: Install kubectl
          run: cd environnement/dev
        - name: Install kubectl
          run: make setup


        # - name: Install kubectl
        #   run: |
        #     KUBECTL_VERSION="v1.30.1"
        #     curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
        #     chmod +x kubectl
        #     sudo mv kubectl /usr/local/bin/kubectl

        # - name: Setup Minikube
        #   uses: medyagh/setup-minikube@latest
        #   with:
        #     kubernetes-version: v1.30.1

        # - name: Set up Helm
        #   uses: azure/setup-helm@v3
        #   with:
        #     version: v3.14.0