name: POC

on:
  push:
    branches: ["**"]     # triggers on ALL branches
  pull_request:
    branches: ["dev"] 

permissions:
  contents: read
  packages: write

jobs:
  minikube:
    name: Run le script de setup-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Stack
        run: |
          cd environnement/dev
          make setup-ci
      - name: Check connectivity log
        run: ls -l /tmp/test-connectivity
      - name: Upload connectivity log
        uses: actions/upload-artifact@v3
        with:
          name: connectivity-log
          path: /tmp/test-connectivity/connectivity.log

        # - name: Install kubectl
        #   run: |
        #     KUBECTL_VERSION="v1.30.1"
        #     curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
        #     chmod +x kubectl
        #     sudo mv kubectl /usr/local/bin/kubectl

        # - name: Setup Minikube
        #   uses: medyagh/setup-minikube@latest
        #   with:
        #     kubernetes-version: v1.30.1

        # - name: Set up Helm
        #   uses: azure/setup-helm@v3
        #   with:
        #     version: v3.14.0